# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creat_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(db_index=True)),
                ('position', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('content', models.TextField(max_length=2000)),
                ('creat_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author_id', models.IntegerField(db_index=True)),
                ('category_id', models.IntegerField(db_index=True)),
                ('creat_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creat_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('creat_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(db_index=True, unique=True)),
                ('name', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('intro', models.TextField(max_length=2000)),
                ('sign', models.TextField(max_length=200)),
                ('creat_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
