# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soyBlog', '0002_auto_20171108_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(max_length=36),
        ),
    ]
