# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soyBlog', '0004_auto_20171109_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
