# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soyBlog', '0005_auto_20171109_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
